name: vancrimewatch
channels:
  - conda-forge
dependencies:
  - pandas
  - ipykernel
  - jupyter
  - shiny
  - python=3.12
  - matplotlib
  - notebook
  - ipyleaflet
  - shinywidgets
  - plotly
  - anywidget